In [1]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [2]:
df=pd.read_csv('/Users/omsitapara/Desktop/DiagnoSafe/Dataset/heart.csv')

In [3]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [4]:
df.shape

(918, 12)

In [5]:
df.duplicated().sum()

0

In [6]:
df.isna().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Sex']=le.fit_transform(df['Sex'])
df['ChestPainType']=le.fit_transform(df['ChestPainType'])
df['RestingECG']=le.fit_transform(df['RestingECG'])
df['ExerciseAngina']=le.fit_transform(df['ExerciseAngina'])
df['ST_Slope']=le.fit_transform(df['ST_Slope'])
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1,1
914,68,1,0,144,193,1,1,141,0,3.4,1,1
915,57,1,0,130,131,0,1,115,1,1.2,1,1
916,57,0,1,130,236,0,0,174,0,0.0,1,1
917,38,1,2,138,175,0,1,173,0,0.0,2,0

In [9]:
X=df.drop(columns='HeartDisease')
Y=df['HeartDisease']
X

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,1,1,140,289,0,1,172,0,0.0,2
1,49,0,2,160,180,0,1,156,0,1.0,1
2,37,1,1,130,283,0,2,98,0,0.0,2
3,48,0,0,138,214,0,1,108,1,1.5,1
4,54,1,2,150,195,0,1,122,0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1
914,68,1,0,144,193,1,1,141,0,3.4,1
915,57,1,0,130,131,0,1,115,1,1.2,1
916,57,0,1,130,236,0,0,174,0,0.0,1
917,38,1,2,138,175,0,1,173,0,0.0,2

In [10]:
Y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2,stratify=Y,random_state=2)
X.shape , X_test.shape , X_train.shape

((918, 11), (184, 11), (734, 11))

In [12]:
sv=svm.SVC(kernel='linear')
sv.fit(X_train,Y_train)
XS_train_pred=sv.predict(X_train)
XS_train_acc=accuracy_score(XS_train_pred,Y_train)
print("SVC Training Accuracy : ", XS_train_acc*100)
XS_test_pred=sv.predict(X_test)
XS_test_acc=accuracy_score(XS_test_pred,Y_test)
print("SVC Testing Accuracy : ", XS_test_acc*100)

SVC Training Accuracy :  85.96730245231608
SVC Testing Accuracy :  85.86956521739131

In [13]:
rf=RandomForestClassifier(n_estimators=100,random_state=42)
rf.fit(X_train,Y_train)
XR_train_pred=rf.predict(X_train)
XR_train_acc=accuracy_score(XR_train_pred,Y_train)
print("RFC Training Accuracy : ", XR_train_acc*100)
XR_test_pred=rf.predict(X_test)
XR_test_acc=accuracy_score(XR_test_pred,Y_test)
print("RFC Testing Accuracy : ", XR_test_acc*100)

RFC Training Accuracy :  100.0
RFC Testing Accuracy :  89.67391304347827

In [14]:
lr=LogisticRegression()
lr.fit(X_train,Y_train)
XL_train_pred=lr.predict(X_train)
XL_train_acc=accuracy_score(XL_train_pred,Y_train)
print("LR Training Accuracy : ", XL_train_acc*100)
XL_test_pred=lr.predict(X_test)
XL_test_acc=accuracy_score(XL_test_pred,Y_test)
print("LR Testing Accuracy : ", XL_test_acc*100)
cm=confusion_matrix(XL_train_pred,Y_train)
print(cm)

LR Training Accuracy :  85.01362397820164
LR Testing Accuracy :  85.32608695652173
[[271  53]
 [ 57 353]]

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [15]:
import pickle

In [16]:
filename='HeartDiseaseTrainedModel.pkl'
pickle.dump(sv,open(filename,'wb'))

In [17]:
heart_model= pickle.load(open('/Users/omsitapara/Desktop/DiagnoSafe/TrainedModel/HeartDiseaseTrainedModel.pkl','rb'))

In [18]:
input_data = (40,1,1,140,289,0,1,172,0,0.0,2)
input_data_array=np.asarray(input_data)
input_data_reshaped = input_data_array.reshape(1,-1)
prediction = heart_model.predict(input_data_reshaped)
print(prediction)
if (prediction[0] == 0):
  print('The person is not likely to have Cardiovascular Disease.')
else:
  print('The person is likely to have Cardiovascular Disease. Confirm the same with a doctor and Take Care.')

[0]
The person is not likely to have Cardiovascular Disease.

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(